### ISSUE TITLE
Ender 5 Plus Stock Display 

### ISSUE THREAD

**Issue by jxlarrea** [patniko/marlin-ender-5-plus#1]
Just read your blog post  and saw this:

> You won’t be able to reuse the stock Ender 5 Plus display

Does that mean that the E5+ display won't work anymore after flashing your firmware? What do you use instead?

**Comment by patniko** [comment]
I use Octoprint at home to control it, but recently installed the TH3D lcd upgrade kit for the plus. Works really well if you are looking for a screen! https://www.th3dstudio.com/product/ender-5-plus-12864-lcd-upgrade-kit/
